config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]

  resources :welcome

  get 'home/home'
  root 'home#home'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
    {
      :subject => "Contact Form",
      :to => "espinozab100@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Sorry Cannot send message.'
      render :new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def home
  
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post,  only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_user!
  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 3)
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Heck Yea Espinoza! Your Article is succesfully Saved!"
    else
      render 'new', notice: "Oh Snap Espinoza! I was unable to save your post. :("
    end
  end

  def show

  end

  def edit

  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Ahhww Yea!!! Your Article was saved succesfully!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project,  only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Awesome Brandon! That project was succesfully saved!"
    else
      render 'new'
    end
  end

  def show
  end

  def edit

  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Ahhww Yea!!! Your Article was saved succesfully!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="page-titles">Why Not Say Hello</h3>
    </div>
  </div>


  <div class="row">
    <div class="col-md-12">
      <h1>Thank you for your message!</h1>
      <p>I'll get back to you soon.</p>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 page-titles no-padding">
      <div class="col-md-8 center-block">
        <h1 class="welcome-header title wow fadeInDown">Why Not Say Hello <span class="comma">,</span></h1>
      </div>
      <div class="col-md-4">
        <h1 class="perspective-p wow fadeInDown"></h1>
        <p class="wow fadeInDown"></p>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-6 center-block panel wow fadeIn" data-wow-duration="3s" style="padding-bottom: 40px;">

      <%= form_for @contact do |f| %>
        <div class="form-group" style="padding: 40px 0 0 0;">
          <%= f.label :name %>
          <%= f.text_field :name, required: true, class: "form-control"  %>
        </div>


        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, required: true, class: "form-control" %>
        </div>


        <div class="form-group">
          <%= f.label :message %>
          <%= f.text_area :message, as: :text, class: "form-control", :cols => "30", :placeholder => "Your Message", :rows => "10" %>
        </div>


        <div class="form-group hidden">
          <%= f.label :nickname %>
          <%= f.text_field :nickname, hint: 'leave this field blank' %>
        </div>


        <%= f.submit 'Yes! Send It!', class: " btn-default btn sendbtn" %>


      <%end%>

    </div>
  </div>
</div>

app/views/home/home.html.erb
<div class="container-fluid home-bg">

  <div id="particles-js"></div>
  <div class="row" style="margin-top: 30vh;">
    <div class="col-md-6 center-block">
      <img src="assets/logo.png" alt="" class="logo wow fadeInDown">
    </div>
    <div class="col-md-12" style="margin-top: 15vh;">
      <!-- <div class="col-md-3 wow fadeInUp">
        <a href="<%= welcome_index_path %>" class="btn btn-home">Photography</a>
      </div> -->
      <div class="col-md-4 wow fadeInUp">
        <a href="<%= projects_path %>" class="btn btn-home">Portfolio</a>
      </div>
      <div class="col-md-4 wow fadeInUp">
        <a href="<%= welcome_index_path %>" class="btn btn-home">About Me</a>
      </div>
      <div class="col-md-4 wow fadeInUp">
        <a href="<%= posts_path %>" class="btn btn-home">Blogs</a>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'particles' %>
<%= javascript_include_tag 'particulas' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web Developer | Web Designer | Brandon Espinoza</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body id="bg">
    <% if current_page?(root_path)%>
      <nav class="navbar navbar-default" style="display: none;">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "BRANDON ESPINOZA", root_path, class: "navbar-brand wow flipInX" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "Perspective", posts_path %>
              </li>
              <li>
                <%= link_to "Projects", projects_path %>
              </li>
              <li>
                <%= link_to "Contact", new_contact_path %>
              </li>
              <li>
                <% if user_signed_in? %>
                  <%= link_to "New Post", new_post_path %>
                  <li>
                    <%= link_to "New Project", new_project_path %>
                  </li>
                  <li>
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                  </li>
                <% else %>
                  <%= link_to "Log In", new_user_session_path %>
                <% end %>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <%end%>

    <% unless current_page?(root_path) %>
      <nav class="navbar second-navbar-default navbar-default">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "BRANDON ESPINOZA", root_path, class: "navbar-brand second-nav-brand wow flipInX" %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "Perspective", posts_path %>
              </li>
              <li>
                <%= link_to "Projects", projects_path %>
              </li>
              <li>
                <%= link_to "Contact", new_contact_path %>
              </li>
              <li>
                <% if user_signed_in? %>
                  <%= link_to "New Post", new_post_path %>
                  <li>
                    <%= link_to "New Project", new_project_path %>
                  </li>
                  <li>
                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                  </li>
                <% else %>
                  <%= link_to "Log In", new_user_session_path %>
                <% end %>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>
    <%end%>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

      <%= yield %>

    <% unless current_page?(root_path) %>
      <footer class="footer">
        <div class="container footer-container">
          <div class="col-md-3 col-sm-4">
            <p class="footer-name"><span style="font-weight: bold;">© 2016 Brandon Espinoza</span></p>
          </div>
          <div class="col-md-2 col-md-offset-1 col-sm-2">
          <%= link_to "Perspective", posts_path, class: "footer-links" %>
          </div>
          <div class="col-md-2 col-sm-2">
              <%= link_to "Projects", projects_path, class: "footer-links" %>
          </div>
          <div class="col-md-2 col-sm-2">
              <%= link_to "Contact", new_contact_path, class: "footer-links" %>
          </div>
          <div class="col-md-2 col-sm-2">
            <a href="https://www.linkedin.com/in/bespinoza10" target="_blank"><i class="fa fa-linkedin-square"></i></a>
            <a href="https://www.github.com/bespinoza10" target="_blank"><i class="fa fa-github"></i></a>
          </div>
        </div>
      </footer>
    <%end%>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {
this.page.url = '<%= url_for([@post, {only_path: false}]) %>'; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.title = '<%= @post.title %>'
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//espinozabrandblogging.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 center-block wow fadeIn" data-wow-duration="3s" style="padding:40px 0 40px 0;">
      <%= form_for @post do |f| %>
        <% if @post.errors.any?%>
          <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <%end%>
          </ul>
        <%end%>
        <div class="form-group">
          <label><%= f.label :title %></label>
          <%= f.text_field :title, {class: 'form-control'}%>
        </div>

        <div class="form-group">
          <label><%= f.label :content %></label>
          <%= f.text_area :content, {class: 'form-control text-area-h'}%>
        </div>
        <button type="submit" class="btn sendbtn">Submit</button>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="page-titles">Edit Post</h3>
    </div>
  </div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container ">
  <div class="row">
    <div class="col-md-12 page-titles no-padding">
      <div class="col-md-8 col-sm-6">
        <h1 class="welcome-header title wow fadeInDown">My Perspective <span class="comma">,</span></h1>
      </div>
      <div class="col-md-4">
        <h1 class="perspective-p wow fadeInDown">The Way I See "Hello World"</h1>
        <p class="wow fadeInDown">... and other stuff.</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 center-block">
      <% @posts.each do |post| %>
        <div class="col-md-12 border">
          <h1 class="wow fadeInUp blog-title" style="text-align:center;"><a href=""><%= link_to post.title, post, class: "blog-name" %></a></h1>
          <p class=" wow fadeInUp dates" style="text-align:center;"><%= post.created_at.strftime('%A, %B %d') %></p>
          <hr class="wow fadeInUp" style="width: 10%;">
        </div>
      <%end%>
      <!-- <hr style="height: 100px; width: 2px;"> -->
    </div>
  </div>

  <div class="row">
    <div class="col-md-12" style="text-align: center; padding-top: 50px;">
      <%= will_paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="page-titles">New Post</h3>
    </div>
  </div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 panel center-block wow fadeInDown" style="margin-top: 5%;">
      <h1 style="text-align: center;"><%= @post.title %></h1>
      <p class="dates" style="text-align:center;"> <%= @post.created_at.strftime("%A, %B %d") %> </p>
      <br>
      <hr>
      <br>
      <p><%= markdown @post.content %></p>
    </div>
    <br>

    <% if user_signed_in? %>
      <div class="col-md-6 center-block admin-links wow fadeInDown">
        <a><%= link_to "Edit", edit_post_path(@post), {class: "btn sendbtn"} %></a>
        <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this poor lonely post? If so HaHa poor post!" }, class: "btn btn-danger" %>
      </div>
    <% end %>

  </div>
  <div class="row" style="padding-bottom: 5%;">
    <hr style="width: 12%;">
    <div class="col-sm-4 center-block wow fadeInDown" style="padding-top: 5%;">
      <h4 style="text-align:center; color: #000;">Share " <%= @post.title %> "</h4>
    </div>
      <!-- Twitter -->
    <div class="col-sm-6 center-block" style="text-align:center; padding-top: 3%;">
      <a onclick="javascript:window.open('https://twitter.com/share?text=<%= @post.title %> by Brandon Espinoza - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);" class="fa-padding"><i class="fa fa-twitter"></i></a>
      <!-- Facebook -->
      <a <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);" class="fa-padding"><i class="fa fa-facebook"></i></a>
      <!-- Google + -->
      <a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-google-plus"></i></a>


    </div>
  </div>

  <div class="row">
    <div class="col-md-10 panel center-block">
      <%= render 'disqus' %>
    </div>
  </div>

</div>

app/views/projects/_form.html.erb
<div class="container">
  <div class="row" style="padding-bottom: 40px;">
    <div class="col-md-10 center-block wow fadeIn" data-wow-duration="3s">
      <%= form_for @project do |f| %>
        <% if @project.errors.any?%>
          <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
          <ul>
            <% @project.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <%end%>
          </ul>
        <%end%>
        <div class="form-group">
          <label><%= f.label :title %></label>
          <%= f.text_field :title, {class: 'form-control'}%>
        </div>

        <div class="form-group">
          <label><%= f.label :description %></label>
          <%= f.text_area :description, {class: 'form-control text-area-h'}%>
        </div>

        <div class="form-group">
          <label><%= f.label :link %></label>
          <%= f.text_field :link, {class: 'form-control'}%>
        </div>

        <button type="submit" class="btn sendbtn">Submit</button>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit Project</h1>
  </div>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 page-titles no-padding">
      <div class="col-md-8">
        <h1 class="welcome-header title wow fadeInDown">My Showcase <span class="comma">,</span></h1>
      </div>
      <div class="col-md-4">
        <h1 class="perspective-p wow fadeInDown">Just Simply Stuff I've Done</h1>
        <p class="wow fadeInDown"></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 center-block">
      <% @projects.each do |project| %>
        <div class="col-md-4 border">
          <h1 style="text-align:center;"><%= link_to project.title, project, class: "blog-name" %></h1>
          <p class="dates" style="text-align:center;"><%= project.created_at.strftime('%A, %B %d') %></p>
          <hr style="width: 10%;">
        </div>
      <%end%>
      <!-- <hr style="height: 100px; width: 2px;"> -->
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3 class="page-titles">New Project</h3>
    </div>
  </div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 center-block panel wow fadeInDown" style="margin-top: 5%;">
      <h1 class="project-title" style="text-align: center;"><%= @project.title %></h1>
      <p class="dates" style="text-align:center;"> <%= @project.created_at.strftime("%A, %B %d") %> </p>
      <br>
      <hr>
      <br>
      <p><%= markdown @project.description %></p>
      <br>
    </div>
    <br>
    <div class="col-md-12" style="text-align:center;">
      <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
    </div>
  </div>
    <% if user_signed_in? %>
      <div class="col-md-3 center-block admin-links" style="padding-top: 20px;">
        <a><%= link_to "Edit", edit_project_path(@project), {class: "btn sendbtn"} %></a>
        <a><%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this poor lonely project? If so HaHa poor project!" }, class: "btn btn-danger" %></a>
      </div>
    <% end %>
      <br>
      <br>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="col-md-12 welcome-margin no-padding">
    <div class="col-md-6">
      <h1 class="welcome-header wow fadeInDown">Hello <span class="comma">,</span></h1>
    </div>
    <div class="col-md-6">
      <p class="welcome-p wow fadeInDown">Hello I am Brandon Espinoza. I am a designer and developer living in the Nashville, TN Area. I design stuff and build websites and web apps for the web. I am very passionate about my work. Every website I build is a new challenge to build something unique and usable. I focus on every detail, everything matters to me. I also use the latest web technologies to create my websites. I don't just develop websites and web apps, but I also do some video editing and video effects.</p>
    </div>
  </div>
</div>

<div class="container-fluid welcome-container">
  <div class="row">
    <div class="container">
      <div class="col-md-12 ">
        <h2 class="section-titles wow fadeInLeft"><span style="font-weight: bold;">.01 </span>Skillset</h2>
        <p class="section-subtitles wow fadeInLeft">Tools I Use The Most In My Projects</p>
        <br>
        <div class="col-md-5 no-padding wow fadeIn">
          <p class="progress-title">HTML</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 col-md-offset-2 wow fadeIn no-padding">
          <p class="progress-title">CSS</p>
          <div class="progress">
            <div class="progress-bar fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 no-padding wow fadeIn">
          <p class="progress-title">JavaScript</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 col-md-offset-2 wow fadeIn no-padding">
          <p class="progress-title">Ruby on Rails</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 no-padding wow fadeIn">
          <p class="progress-title">Twitter Bootstrap</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 col-md-offset-2 wow fadeIn no-padding">
          <p class="progress-title">Zurb Foundation</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 no-padding wow fadeIn">
          <p class="progress-title">Github</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 90%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 col-md-offset-2 wow fadeIn no-padding">
          <p class="progress-title">Heroku</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 no-padding wow fadeIn">
          <p class="progress-title">Adobe Photoshop</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 85%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 wow col-md-offset-2 fadeIn no-padding">
          <p class="progress-title">Adobe Premiere Pro</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
            </div>
          </div>
        </div>
        <div class="col-md-5 no-padding wow fadeIn">
          <p class="progress-title">Adobe Lightroom</p>
          <div class="progress">
            <div class="progress-bar wow fadeInLeft" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
            </div>
          </div>
        </div>
      </div>
      
      <div class="col-md-12 padding-top">
        <div class="col-md-6 no-padding wow fadeInLeft per-pro-padding">
          <h2 class="section-titles"><span style="font-weight: bold;">.02 </span>My Perspective</h2>
          <hr align="left">
          <div class="col-md-12 wow fadeInLeft">
            <% @posts.each do |post| %>
              <h3><a><%= link_to post.title, post, class: "welcome-links" %></a></h3>
              <p class="dates"> <%= post.created_at.strftime("%A, %b %d") %> </p>
            <% end %>
          </div>
        </div>
        <div class="col-md-5 col-md-offset-1 wow fadeInRight no-padding per-pro-padding">
          <h2 class="section-titles"><span style="font-weight: bold;">.03 </span>My Projects</h2>
          <hr align="left">

          <div class="col-md-12 wow fadeInRight">
            <% @projects.each do |project| %>
              <h3><a> <%= link_to project.title, project, class: "welcome-links" %></a></h3>
              <p class="dates"> <%= project.created_at.strftime("%A, %b %d") %> </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>